import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Chef Ya!",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className="min-h-screen grid grid-rows-[auto_1fr_1fr_auto]">{children}</body>
    </html>
  );
}
